module.exports = {
  rptKontrakPerjanjian: require('./template_files/kontrak-perjanjian'),
  rptKontrakAdendum: require('./template_files/kontrak-adendum'),
  rptKontrakSuratJatuhTempo: require('./template_files/surat-jatuh-tempo'),
  rptKontrakPenghuniRusun: require('./template_files/penghuni-rusun-jenis-kelamin'),
  rptKontrakMonitoringPembayaranListrikAir: require('./template_files/pembayaran-listrik-air'),
  rptKontrakPenghuniRusunPerusahaan: require('./template_files/penghuni-rusun-perusahaan'),
  rptKontrakMonitorPerjanjianSewa: require('./template_files/monitor-perjanjian-sewa'),
  rptKontrakReportWorkOrder: require('./template_files/report-work-order'),
  rptKontrakReportWoAssign: require('./template_files/report-wo-assign'),
  rptKontrakMonitorKamarRusunawa: require('./template_files/monitor-kamar-rusunawa'),
  rptKontrakMonitorPembayaranSewaKmr: require('./template_files/monitoring-pembayaran-sewa-kamar'),
  rptKontrakPenghuniRusunStatusPerkawinan: require('./template_files/penghuni-rusun-status-perkawinan'),
  rptPemberitahuanTagihan: require('./template_files/pemberitahuan-tagihan'),
  rptLampiranCheckoutWo: require('./template_files/lampiran-checkout-wo'),
  rptAvailabilityStatusUnitPerLantai: require('./template_files/availability-status-unit-lantai'),
  rptgetTingkatHunian: require('./template_files/tingkat-hunian'),
  rptSuratTugas: require('./template_files/report-surat-tugas'),
  rptBillingEntriTagihan: require('./template_files/monitor-billing-entri-tagihan'),
}
